### ISSUE TITLE
Not build for debian 10 64

### ISSUE THREAD

**Issue by ediazrod** [backuppc/rsync-bpc#13]
Hi rsync bpc is not build for debian. for the last release, the beta works ok

the error on make is.

gcc -I. -I. -I./zlib -I./popt -g -O2 -DHAVE_CONFIG_H -Wall -W  -c lib/sysacls.c -o lib/sysacls.o
lib/sysacls.c:2761:2: error: #error No ACL functions defined for this platform!
 #error No ACL functions defined for this platform!
  ^~~~~
make: *** [Makefile:65: lib/sysacls.o] Error 1

**Comment by craigbarratt** [comment]
If you build from source you need to install libacl1-dev.

**Comment by MidUK** [comment]
I'm having the same issue too and I've got both libacl1-dev and libacl installed.

lib/sysacls.c:2761:2: error: #error No ACL functions defined for this platform!
 #error No ACL functions defined for this platform!

**Comment by craigbarratt** [comment]
Did you re-run `configure` after installing those packages?

**Comment by MidUK** [comment]
Thanks craigbarratt - that solved the problem.

**Comment by raoulbhatia** [comment]
@craigbarratt I think this issue can be closed per the previous comment.

**Comment by craigbarratt** [comment]
Ok, thanks - closing.

**Comment by picklesrein** [comment]
I ran into this issue when trying to build rsync-bpc on AlmaLinux 9.0. I'm not a programmer so I'm not certain how good of a solution this was, but I couldn't find libacl1-dev so installed this instead:
~~~
dnf install libacl-devel
~~~
then I re-ran `./configure` as mentioned above and `make` completed without error.
HTH!
