### ISSUE TITLE
which Version to choose ?

### ISSUE THREAD

**Issue by flece** [backuppc/rsync-bpc#14]
master is based on rsync-3.1.3 ... Anno 2018
3.1.2  is based on rsync-3.1.2 ... Anno 2015
3.0.9  is based on rsync-3.0.9 ... Anno 2011

i like to go with the latest stable Version. but i dont like to have an 11 years old rsync

why is 3.0.9 the latest stable and not 3.1.2 ?
Is there any reason not to use 3.1.2 ?

thx flece

**Comment by craigbarratt** [comment]
3.1.2 should be fine.  I just haven't gotten around to releasing it.
