### ISSUE TITLE
options.c, Message "BackupPC options are compulsory for running rsync_bpc\n" is not printed

### ISSUE THREAD

**Issue by bitranox** [backuppc/rsync-bpc#22]
while hunting down my problem that permissions are not correct on rsyncd restores, 
I came across following error : 

while playing around I noticed that the message "BackupPC options are compulsory for running rsync_bpc\n" is not printed.

options.c, Line 1880: 

```
        if ( !bpc_top_dir || !bpc_host_name || !bpc_share_name || bpc_backup_num < 0 ) {
            snprintf(err_buf, sizeof(err_buf), "BackupPC options are compulsory for running rsync_bpc\n");
            exit_cleanup(RERR_SYNTAX);
        }
```

I am not a "C" Programmer, but I guess it should be : 

```
            snprintf(err_buf, sizeof err_buf, "BackupPC options are compulsory for running rsync_bpc\n");
```

**Comment by craigbarratt** [comment]
Thanks for the reporting this issue.  The error message is correct, but the `exit()` doesn't print it - it just prints a generic error message.  The correct solution is to just do a `return 0` and the message will get printed before exit.
