### ISSUE TITLE
lib/sysacls.c throws error when no ACLs defined

### ISSUE THREAD

**Issue by johnd486** [backuppc/rsync-bpc#27]
``` lib/sysacls.c:2761:2: error: #error No ACL functions defined for this platform!
 2761 | #error No ACL functions defined for this platform!
      |  ^~~~~
make: *** [Makefile:65: lib/sysacls.o] Error 1
```
OK so there are no ACLs defined. How would you suggest the user corrects that please?

I'm running Ubuntu 21.10 with an existing SAMBA server supporting MacOS shares and Time Machine.

**Comment by ediazrod** [comment]
It was solve here.. https://github.com/backuppc/rsync-bpc/issues/13

**Comment by johnd486** [comment]
Awesome, thank you Eduardo, that fixed the problem!


On 31 Oct 2021, at 16:03, Eduardo Diaz ***@***.***> wrote:

﻿
It was solve here.. #13

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ediazrod** [comment]
No problem, please close the issue.
